selenium-hub:
  image: selenium/hub:3.4.0-chromium
  ports:
    - "4444:4444"

chrome:
    image: selenium/node-chrome-debug:3.4.0-chromium
    links:
      - selenium-hub:hub
    ports:
      - "5901:5900"

chrome:
    image: selenium/node-chrome-debug:3.4.0-chromium
    links:
      - selenium-hub:hub
    ports:
      - "5903:5900"
firefox:
    image: selenium/node-firefox-debug:3.4.0-chromium
    links:
      - selenium-hub:hub
    ports:
      - "5902:5900"
